
## PAO25-25- Examen

![logo](img/python_logo.png)
*ESTUDIANTE: IVAN LISINTUÑA*
<br>
*link de git hub:https://github.com/GOJO551/Ejercios-marchine.git*

In [14]:
import numpy as np
import pandas as pd

## 01 - 1 pt
- Dado un array de elementos, escribir una función, que reciba dicho array como parámetro de entrada y devuelva el elemento repetido. Usando plain Python, sin ninguna librería.

In [7]:
import math
array_src = [4, 8, 0, 3, 6, 2, 1, 5, 3, 9, 7]
expected_rep_element = 3
rep_element = repeated_element(array_src) # This calls your function repeated_element
assert(expected_rep_element == rep_element)  # This will fail if the element is not found correctly

NameError: name 'repeated_element' is not defined

In [1]:
# Your solution HERE !!!!

In [6]:
def rep_element(init, step):
    while True:
        yield arrays_src
        arrys_src+= expexted_rep_elemnt

In [17]:
# esto es hecho por chat
def repeated_element(arr):
    seen = set()  # conjunto para guardar elementos ya vistos
    for elem in arr:
        if elem in seen:
            return elem  # si ya lo vimos, lo devolvemos
        seen.add(elem)
    return None  # si no hay repetidos

# Prueba con el array dado
array_src = [4, 8, 0, 3, 6, 2, 1, 5, 3, 9, 7]
expected_rep_element = 3
rep_element = repeated_element(array_src)

print("Elemento repetido:", rep_element)

assert(expected_rep_element == rep_element)



Elemento repetido: 3


## 02 - 1pt
- Genera una matriz con valores aleatorios de 0 a 100 de dimensiones 16x16
- Calcula los siguentes estadísticos en la matriz anterior, por fila (el resultado de cada uno debe ser un array de dimensiones 1x16)
  - Suma de los elementos de cada fila
  - Media de los elementos de cada fila
  - Valores mínimos de cada fila
  - Valores máximos de cada fila

In [18]:
matriz = np.random.randint(0, 101, size=(16, 16))
suma_filas = matriz.sum(axis=1)
media_filas = matriz.mean(axis=1)
min_filas = matriz.min(axis=1)
max_filas = matriz.max(axis=1)
print("Matriz:\n", matriz)
print("\nSuma por fila:", suma_filas)
print("\nMedia por fila:", media_filas)
print("\nMínimos por fila:", min_filas)
print("\nMáximos por fila:", max_filas)


Matriz:
 [[ 92  89  46  65  50  18  50  43   2  58  87  38  13  19  13  24]
 [ 48  25   6  95  10  28  37  18  45  65  10  32  94  17  68  30]
 [ 96  55  15  82  14  66  99  12  22  58  33  56  50  13  83  11]
 [ 66  96  62   8   7   6  39  72  13  68  60  98  36 100  25  68]
 [ 62  10  97  15  49  10  38  69   4   6  13  85  39  36  29  23]
 [ 30  31  40  41  75  86  24  30  15  26  14  89  81  92  52  32]
 [ 76  73  45  21  60  72  42  34  12   0  99  50  74  92   6  90]
 [ 24   4  53  12  32  70  39  19  10  15  21  86  29   4  90  28]
 [ 48  53  37  83  25  74  89  15  61  18  99  79  15  52   7  91]
 [ 71  67  70  35  11  27  22  73  12 100  69 100  48  16  23  13]
 [ 94  15  33  15  82  52  88  48  52  59  73  65  77  18  53  93]
 [ 92  82  43  46  84  25  96  63  28  12  39  95  24  15  79  10]
 [ 71  62  96  50  30  90  84  95  73   6  71  89  46  64  10   6]
 [ 26  94  26  66  77  47  25  86  51  98  64  25  31  62  83  47]
 [ 97  67  97  38  43  47  71  96  18  12  86  29  82

## 03 - 1pt

- Generar un dataframe de 3x4 dimensiones con valores númericos aleatorios [0,10]
- Darle un índice semántico alfanumérico
- Aplicarle una función lambda que obtenga la diferencia entre el máximo y mínimo de cada fila

In [19]:
df = pd.DataFrame(np.random.uniform(0, 10, size=(3,4)))
df.index = ['A', 'B', 'C']
print("DataFrame original:")
print(df)
diferencia = df.apply(lambda fila: fila.max() - fila.min(), axis=1)
print("\nDiferencia entre máximo y mínimo por fila:")
print(diferencia)


DataFrame original:
          0         1         2         3
A  5.832974  6.797043  8.566209  7.453277
B  9.204913  9.638071  3.856636  1.615454
C  2.834891  6.184227  8.118141  7.798673

Diferencia entre máximo y mínimo por fila:
A    2.733235
B    8.022616
C    5.283250
dtype: float64


## 04 - 1pt
- Crear un array de NumPy de dimensiones 8x5, con números enteros aleatorios en el rango [-100, 100]
- Ejecutar en este orden

  1. Reemplazar los valores de todos aquellos números múltiplos de 5 por 100
  2. Reemplazar los valores de todos aquellos números múltiplos de 3 por Nan
   
  2. Averiguar cuantos elementos tienen Nan por fila
  3. Reemplazar los valores de Nan por 0

In [21]:
#hecho por chat
import numpy as np

# 1. Crear array 8x5 con enteros aleatorios entre -100 y 100
arr = np.random.randint(-100, 101, size=(8,5)).astype(float)  # paso a float para poder usar NaN

print("Array original:")
print(arr)

# 2. Reemplazar múltiplos de 5 por 100
arr[arr % 5 == 0] = 100

# 3. Reemplazar múltiplos de 3 por NaN (ojo que los múltiplos de 15 ya serán 100, así que no cambiarán)
# Para que no se pisen, primero los múltiplos de 5 ya cambiados a 100 no serán múltiplos de 3,
# porque 100 % 3 != 0. Así que podemos hacer:
arr[(arr % 3 == 0) & (arr != 100)] = np.nan

print("\nArray después de reemplazos:")
print(arr)

# 4. Contar NaN por fila
nan_por_fila = np.isnan(arr).sum(axis=1)
print("\nCantidad de NaN por fila:")
print(nan_por_fila)

# 5. Reemplazar NaN por 0
arr[np.isnan(arr)] = 0

print("\nArray final con NaN reemplazados por 0:")
print(arr)


Array original:
[[ 72.   0.  75. -38. -57.]
 [ 16. -56.  92.  51.   5.]
 [ 66.  46. -41. -84.   7.]
 [-10. -90.  29.  61. -80.]
 [-58.  10.  75.  30.  -2.]
 [ 90. -96. -46.   9.  -4.]
 [ 75.  92.   5. -41.  32.]
 [-84.  47.  93.  88. -10.]]

Array después de reemplazos:
[[ nan 100. 100. -38.  nan]
 [ 16. -56.  92.  nan 100.]
 [ nan  46. -41.  nan   7.]
 [100. 100.  29.  61. 100.]
 [-58. 100. 100. 100.  -2.]
 [100.  nan -46.  nan  -4.]
 [100.  92. 100. -41.  32.]
 [ nan  47.  nan  88. 100.]]

Cantidad de NaN por fila:
[2 1 2 0 0 2 0 2]

Array final con NaN reemplazados por 0:
[[  0. 100. 100. -38.   0.]
 [ 16. -56.  92.   0. 100.]
 [  0.  46. -41.   0.   7.]
 [100. 100.  29.  61. 100.]
 [-58. 100. 100. 100.  -2.]
 [100.   0. -46.   0.  -4.]
 [100.  92. 100. -41.  32.]
 [  0.  47.   0.  88. 100.]]


## 05 - 1pt
- Crear una función que reciba una lista de strings y devuelva una serie de pandas, y convierta el primer y último carácter de la palabra de cada elemento de la serie a mayúsculas

In [23]:
languages = ['python', 'php', 'java', 'javascript', 'c++', 'sql']
expected_output = pd.Series(['PythoN', 'PhP', 'JavA', 'JavascripT', 'C++', 'SqL'])
output = first_last_uppercase(languages)  # This calls your function first_last_uppercase
assert(expected_output.equals(output))  # This will fail if the two lists are different

In [33]:
#hexcho por chat
def first_last_uppercase(lst):
    # Crear la serie a partir de la lista
    serie = pd.Series(lst)
    
    # Función auxiliar para modificar cada string
    def modificar_palabra(palabra):
        if len(palabra) == 1:
            # Si la palabra es un solo carácter, solo mayúscula ese carácter
            return palabra.upper()
        else:
            # Mayúscula el primer y último carácter, y deja el resto igual
            return palabra[0].upper() + palabra[1:-1] + palabra[-1].upper()
    
    # Aplicar la función a cada elemento de la serie
    serie_modificada = serie.apply(modificar_palabra)
    return serie_modificada
print(output)

assert(expected_output.equals(output))


0        PythoN
1           PhP
2          JavA
3    JavascripT
4           C++
5           SqL
dtype: object


## 07 - 1pt
- La serie de Fibonacci es una sucesión de números, en la cual cada número es la suma de los dos anteriores. Los dos primeros son siempre 0 y 1.
  - $F_0 = 0$
  - $F_1 = 1$
  - $F_n = F_{n-1} + F_{n-2}$
- Crear un generador infinito de números de Fibonacci.

In [26]:
fibo = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
g = fibonacci_generator()  # This calls tour function fibonacci_generator
expected_output = [next(g) for n in range(len(fibo))]
assert(fibo == expected_output)  # This will fail if the output is not as expected

In [29]:
#hecho por chat
def fibonacci_generator():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

# Prueba:
fibo = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597]
g = fibonacci_generator()
expected_output = [next(g) for _ in range(len(fibo))]

print(expected_output)
assert(fibo == expected_output)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]


## 07 - 4pt
- Crear una lista de meses de Enero a Diciembre (eje X)
- Generar datos aleatorios para el eje Y, hacerlo 3 veces distintas (Y0, Y1 e Y2)
- Representar las 3 secuencias de datos aleatorios en una sola figura usando matplotlib
- Añadir una leyenda para poder identificar cada secuencia
- Nombrar las 3 secuencias de la siguiente manera ("Facebook", "Twitter", "Instagram")
- Añadir un título y nombres a los dos ejes
- Añadir una anotación (texto y flecha) a uno de los gráficos

In [28]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Lista de meses (eje X)
meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 
         'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

# 2. Generar 3 secuencias de datos aleatorios para Y
np.random.seed(42)  # para reproducibilidad
Y0 = np.random.randint(50, 200, size=12)
Y1 = np.random.randint(30, 150, size=12)
Y2 = np.random.randint(80, 250, size=12)

# 3. Crear la figura y el eje
fig, ax = plt.subplots(figsize=(12, 6))

# 4. Graficar las 3 secuencias
ax.plot(meses, Y0, marker='o', label='Facebook')
ax.plot(meses, Y1, marker='s', label='Twitter')
ax.plot(meses, Y2, marker='^', label='Instagram')

# 5. Añadir título y nombres a los ejes
ax.set_title('Datos de Redes Sociales por Mes')
ax.set_xlabel('Meses')
ax.set_ylabel('Número de Interacciones')

# 6. Añadir leyenda
ax.legend()

# 7. Añadir anotación (flecha y texto) en la serie de Facebook, por ejemplo en el mes de Mayo
mes_anotacion = 'Mayo'
indice_mayo = meses.index(mes_anotacion)
valor_mayo = Y0[indice_mayo]

ax.annotate('Pico en Mayo',
            xy=(indice_mayo, valor_mayo),  # punto a señalar
            xytext=(indice_mayo + 1, valor_mayo + 40),  # posición del texto
            arrowprops=dict(facecolor='black', shrink=0.05),
            fontsize=12,
            ha='left')

# Mejorar visualización rotando etiquetas x
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()


ModuleNotFoundError: No module named 'matplotlib'